package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"
	"giftjob-backend/graph/model"
)

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}

// GetTemplate is the resolver for the getTemplate field.
func (r *queryResolver) GetTemplate(ctx context.Context, id string) (*model.CompanyCustomTemplate, error) {
	panic(fmt.Errorf("not implemented: GetTemplate - getTemplate"))
}

// GetCompany is the resolver for the getCompany field.
func (r *queryResolver) GetCompany(ctx context.Context, id string) (*model.Company, error) {
	panic(fmt.Errorf("not implemented: GetCompany - getCompany"))
}

// GetPerson is the resolver for the getPerson field.
func (r *queryResolver) GetPerson(ctx context.Context, id string) (*model.Person, error) {
	panic(fmt.Errorf("not implemented: GetPerson - getPerson"))
}

// GetNote is the resolver for the getNote field.
func (r *queryResolver) GetNote(ctx context.Context, id string) (*model.Note, error) {
	panic(fmt.Errorf("not implemented: GetNote - getNote"))
}

// GetCalendar is the resolver for the getCalendar field.
func (r *queryResolver) GetCalendar(ctx context.Context, id string) (*model.Calendar, error) {
	panic(fmt.Errorf("not implemented: GetCalendar - getCalendar"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
